name: 3dvlp
channels:
  - <unknown>
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - cffi=1.17.0
  - cpython=3.8.20
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.3.1
  - dav1d=1.2.1
  - ffmpeg=7.1.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.14
  - h2=4.1.0
  - harfbuzz=12.2.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - intel-openmp=2022.1.0
  - jinja2=3.1.4
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.44
  - libabseil=20240722.0
  - libass=0.17.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=5.28.2
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.2.0
  - libuuid=2.41.2
  - libuv=1.51.0
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.1
  - ninja=1.13.1
  - numpy=1.24.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.4.1
  - openssl=3.5.4
  - pcre2=10.46
  - pillow=9.3.0
  - pip=24.3.1
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.14
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.8.20
  - python_abi=3.8
  # - pytorch=2.0.0
  # - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=75.3.0
  - snappy=1.2.2
  - svt-av1=2.2.1
  - sympy=1.13.3
  - tbb=2022.3.0
  - tk=8.6.13
  # - torchaudio=2.0.0
  # - torchtriton=2.0.0
  # - torchvision=0.15.0
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.4.9
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - cachetools==5.5.2
      - certifi==2025.10.5
      - charset-normalizer==3.3.0
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - easydict==1.13
      - eval-type-backport==0.2.2
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - llvmlite==0.41.1
      - markdown==3.7
      - matplotlib==3.7.5
      - numba==0.58.1
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - platformdirs==4.3.6
      - plyfile==1.0.3
      - protobuf==4.25.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentry-sdk==2.43.0
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tokenizers==0.13.3
      # - torch-scatter==2.1.2+pt20cu118
      - tqdm==4.67.1
      - transformers==4.31.0
      - trimesh==2.35.39
      - tzdata==2025.2
      - wandb==0.22.3
      - werkzeug==3.0.6
      - zipp==3.20.2
